name: Build HealthCheck UI docker image

on:
  push #:
    #branches:
    #  - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Determine semantic version
        uses: dotnet/nbgv@master
        id: nbgv
        with:
          setAllVars: true

      - name: Set versions
        run: |
          echo "version1=${{steps.nbgv.outputs.VersionMajor}}" >> $GITHUB_ENV
          echo "version2=${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}" >> $GITHUB_ENV
          echo "version3=${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}.${{steps.nbgv.outputs.BuildNumber}}" >> $GITHUB_ENV
          echo "version4=${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}.${{steps.nbgv.outputs.BuildNumber}}${{steps.nbgv.outputs.PrereleaseVersion}}" >> $GITHUB_ENV
          echo "version5=${{steps.nbgv.outputs.VersionMajor}}.${{steps.nbgv.outputs.VersionMinor}}.${{steps.nbgv.outputs.BuildNumber}}${{steps.nbgv.outputs.PrereleaseVersion}}.${{steps.nbgv.outputs.VersionHeight}}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build Main Dockerfile
        uses: docker/build-push-action@v2
        with:
          push: true
          file: build/docker-images/HealthChecks.UI.Image/Dockerfile
          build-args: |
            version=${{ env.version4 }}
            versionHeight=${{steps.nbgv.outputs.VersionHeight}}
          tags: |
            ghcr.io/exram/aspnetcore.diagnostics.healthchecks.ui:${{ env.version1 }}
            ghcr.io/exram/aspnetcore.diagnostics.healthchecks.ui:${{ env.version2 }}
            ghcr.io/exram/aspnetcore.diagnostics.healthchecks.ui:${{ env.version3 }}
            ghcr.io/exram/aspnetcore.diagnostics.healthchecks.ui:${{ env.version4 }}
            ghcr.io/exram/aspnetcore.diagnostics.healthchecks.ui:${{ env.version5 }}

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.3
        with:
          custom_tag: AspNetCore.Diagnostics.HealthChecks.UI-Docker-${{ env.version5 }}
          github_token: ${{ secrets.GITHUB_TOKEN }}